[TcpInput]
address = "127.0.0.1:5565"
parser_type = "message.proto"
decoder = "ProtobufDecoder"

[CounterFilter]
message_matcher = "Type != 'heka.counter-output'"
ticker_interval = 1

[LogOutput]
message_matcher = "Type == 'heka.counter-output' || Type == 'heka.all-report'"
payload_only = true
